### ISSUE TITLE
DAO's 60-66

### ISSUE THREAD

**Issue by GriffGreen** [dsystems-io/childDaoRefund#1]
How did you verify that the childDAOs that were created using proposals 60-66 were able to get 1 ETH for every 100 DAO tokens burned?

**Comment by dsystems-io** [comment]
Not all of them did, 62 did not split in time.

I looked through each of the splitDAO() calls that sent ETH into those contracts and verified that the number of tokens burned was 100:1 for the amount of ETH sent. For instance, the last splitDAO() TX on proposal 63 is this one: https://etherscan.io/tx/0x36114a364d26bd5465b766425ebf6f9a7e8d74a8a8697b72b297f1ce6171c695

You can see that 55,936.99 DAO were burned and 559.37 ETH were sent to the childDAO. This is true for each of the childDAOs I included in the whitelist. Would be great if someone could double check to ensure I didn't miss any TXs.

**Comment by GriffGreen** [comment]
Awesome. The token/eth ratio is determined the first time someone calls splitDAO, so if one transaction has 100 to 1 then they all do :-)
